import type { Research } from './types';
// Reviewed planning milestones. Prices retain the demo's 5 gold per research-hour convention.
export const EXTRA_RESEARCH: Research[] = [
  {
    id: 'revivalClass',
    name: 'Revival class',
    description:
      'Unlock a 10-gold healer course, paid from their wealth before joining a party. Revive within 00:05 at half health for two-thirds maximum stamina. Base cast: 00:01 at speed 10.',
    hours: 1,
    cost: 500,
    icon: 'training',
  },
  ...[3, 4, 5].map((t) => ({
    id: `building${t}`,
    name: ['Stonecraft mastery', 'Runic foundations', 'The deep citadel'][t - 3],
    description: `Upgrade floors to level ${t}: ${t * 10} health and defense, new architecture. Builders start at the deepest floor.`,
    hours: 2 ** (t - 1),
    cost: 500 * 2 ** (t - 1),
    icon: 'depths',
  })),
  ...[2, 3, 4].map((t) => ({
    id: `builders${t}`,
    name: ['Better Builders', 'Even Better Builders', 'The Best Builders'][t - 2],
    description: `Hire builder tier ${t}. Speed ${t === 4 ? 45 : t * 10}; hire cost ${t * 5} gold; hiring cap ${t === 4 ? 25 : t * 5}.`,
    hours: 2 ** (t - 1),
    cost: 500 * 2 ** (t - 1),
    icon: 'builders',
  })),
  ...[3, 4, 5].map((t) => ({
    id: `traps${t}`,
    name: `Trap engineering ${t}`,
    description: `Unlock tier ${t} trapdoors, arrow walls and mimics. Upgrade individual fixtures in the floor editor.`,
    hours: [8, 12, 16][t - 3],
    cost: [4000, 6000, 8000][t - 3],
    icon: 'traps',
  })),
  ...[2, 3, 4, 5].map((t) => ({
    id: `mobs${t}`,
    name: `Monster husbandry ${t}`,
    description: `Unlock level ${t} zombies, slimes and their spawners.`,
    hours: [4, 8, 12, 16][t - 2],
    cost: 2000 * (t - 1),
    icon: 'mobs',
  })),
  ...[2, 3, 4, 5].map((t) => ({
    id: `staff${t}`,
    name: `Professional crew ${t}`,
    description: `Unlock tier ${t} maintenance and defender training. Office training preserves earned growth. Training costs ${[10, 10, 15, 20][t - 2]} gold.`,
    hours: 4 * (t - 1),
    cost: 2000 * (t - 1),
    icon: 'staff',
  })),
  ...[3, 4, 5].map((t) => ({
    id: `adventurers${t}`,
    name: `Level ${t} adventurers`,
    description: `Unlock tier ${t} arrival points with ${t}× base stats and a ${[50, 75, 75][t - 3]}% spawn interval reduction.`,
    hours: 4 * (t - 1),
    cost: 2000 * (t - 1),
    icon: 'adventurers',
  })),
  ...[2, 3, 4].map((t) => ({
    id: `rest${t}`,
    name: ['Comfortable Bunks', 'Restorative suites', 'Luxury Suits'][t - 2],
    description: `Visitor rooms ${t}: recover ${t + 1} resource points per hour; default fee ${t} gold. Staff room tier ${Math.min(t, 3)}.`,
    hours: [4, 8, 10][t - 2],
    cost: [2000, 4000, 5000][t - 2],
    icon: 'rest',
  })),
  {
    id: 'betterTreasure',
    name: 'Better basic treasure',
    description:
      'Wood difficulty +5, silver +10. Each eligible character gets one attempt with 1/3 success.',
    hours: 1,
    cost: 500,
    icon: 'treasure',
  },
  {
    id: 'crystalChests',
    name: 'Crystal chests',
    description: 'Unlock teal crystal chests; 1/5 opening chance per eligible character.',
    hours: 12,
    cost: 6000,
    icon: 'treasure',
  },
  {
    id: 'royalChests',
    name: 'Royal chests',
    description: 'Unlock crowned gold chests; 1/6 opening chance per eligible character.',
    hours: 16,
    cost: 8000,
    icon: 'treasure',
  },
  {
    id: 'toolbelts',
    name: 'Organized toolbelts',
    description: 'Maintenance reset skill +5.',
    hours: 4,
    cost: 2000,
    icon: 'staff',
  },
  {
    id: 'resetKits',
    name: 'Precision reset kits',
    description: 'Reset skill +10, replacing the toolbelt bonus.',
    hours: 8,
    cost: 4000,
    icon: 'staff',
  },
  {
    id: 'containment',
    name: 'Please remain inside',
    description: 'Mob exit success falls to 10%.',
    hours: 4,
    cost: 2000,
    icon: 'mobs',
  },
  {
    id: 'containment2',
    name: 'Strictly indoor monsters',
    description: 'Mob exit success falls to 5%.',
    hours: 8,
    cost: 4000,
    icon: 'mobs',
  },
  {
    id: 'guild3',
    name: 'Regional Adventurers Guild',
    description:
      '40% shorter spawn intervals; +40 population capacity; parties form in 10 real seconds. Strongest interval reduction applies.',
    hours: 8,
    cost: 4000,
    icon: 'adventurers',
  },
  {
    id: 'regionalAds',
    name: 'Regional ads',
    description: 'Buy two more arrival points, up to five total. Each adds 10 population capacity.',
    hours: 8,
    cost: 4000,
    icon: 'adventurers',
  },
  {
    id: 'unpaidOvertime',
    name: 'Unpaid overtime',
    description:
      'Staff hiring costs 1 gold less; working defender wages fall by 0.5 gold per hour.',
    hours: 4,
    cost: 2000,
    icon: 'finance',
  },
  {
    id: 'guildGrant',
    name: 'Guild Grant',
    description:
      'Collect 1 extra gold for each adventurer stat point gained at a floor checkpoint, limited by party wealth.',
    hours: 8,
    cost: 4000,
    icon: 'finance',
  },
] as Research[];
