// Pre-baked PNG strips shared by web, iOS and Android.
import { ActionKind } from './actionFrames';
export const ACTION_IMAGES: Record<ActionKind | `${ActionKind} effect`, number[]> = {
  'Lightning spell': [
    require('../../assets/actions/lightning-spell-1.png'),
    require('../../assets/actions/lightning-spell-2.png'),
    require('../../assets/actions/lightning-spell-3.png'),
    require('../../assets/actions/lightning-spell-4.png'),
    require('../../assets/actions/lightning-spell-5.png'),
  ],
  'Lightning spell effect': [
    require('../../assets/actions/lightning-spell-effect-1.png'),
    require('../../assets/actions/lightning-spell-effect-2.png'),
    require('../../assets/actions/lightning-spell-effect-3.png'),
    require('../../assets/actions/lightning-spell-effect-4.png'),
    require('../../assets/actions/lightning-spell-effect-5.png'),
  ],
  'Waiting for rest': [
    require('../../assets/actions/waiting-for-rest-1.png'),
    require('../../assets/actions/waiting-for-rest-2.png'),
    require('../../assets/actions/waiting-for-rest-3.png'),
    require('../../assets/actions/waiting-for-rest-4.png'),
    require('../../assets/actions/waiting-for-rest-5.png'),
  ],
  'Waiting for rest effect': [
    require('../../assets/actions/waiting-for-rest-effect-1.png'),
    require('../../assets/actions/waiting-for-rest-effect-2.png'),
    require('../../assets/actions/waiting-for-rest-effect-3.png'),
    require('../../assets/actions/waiting-for-rest-effect-4.png'),
    require('../../assets/actions/waiting-for-rest-effect-5.png'),
  ],
  'Reset trap': [
    require('../../assets/actions/reset-trap-1.png'),
    require('../../assets/actions/reset-trap-2.png'),
    require('../../assets/actions/reset-trap-3.png'),
    require('../../assets/actions/reset-trap-4.png'),
    require('../../assets/actions/reset-trap-5.png'),
  ],
  'Reset trap effect': [
    require('../../assets/actions/reset-trap-effect-1.png'),
    require('../../assets/actions/reset-trap-effect-2.png'),
    require('../../assets/actions/reset-trap-effect-3.png'),
    require('../../assets/actions/reset-trap-effect-4.png'),
    require('../../assets/actions/reset-trap-effect-5.png'),
  ],
  'Mob spawning': [
    require('../../assets/actions/mob-spawning-1.png'),
    require('../../assets/actions/mob-spawning-2.png'),
    require('../../assets/actions/mob-spawning-3.png'),
    require('../../assets/actions/mob-spawning-4.png'),
    require('../../assets/actions/mob-spawning-5.png'),
  ],
  'Mob spawning effect': [
    require('../../assets/actions/mob-spawning-effect-1.png'),
    require('../../assets/actions/mob-spawning-effect-2.png'),
    require('../../assets/actions/mob-spawning-effect-3.png'),
    require('../../assets/actions/mob-spawning-effect-4.png'),
    require('../../assets/actions/mob-spawning-effect-5.png'),
  ],
  'Adventurer spawning': [
    require('../../assets/actions/adventurer-spawning-1.png'),
    require('../../assets/actions/adventurer-spawning-2.png'),
    require('../../assets/actions/adventurer-spawning-3.png'),
    require('../../assets/actions/adventurer-spawning-4.png'),
    require('../../assets/actions/adventurer-spawning-5.png'),
  ],
  'Adventurer spawning effect': [
    require('../../assets/actions/adventurer-spawning-effect-1.png'),
    require('../../assets/actions/adventurer-spawning-effect-2.png'),
    require('../../assets/actions/adventurer-spawning-effect-3.png'),
    require('../../assets/actions/adventurer-spawning-effect-4.png'),
    require('../../assets/actions/adventurer-spawning-effect-5.png'),
  ],
  'Fighter attack': [
    require('../../assets/actions/fighter-attack-1.png'),
    require('../../assets/actions/fighter-attack-2.png'),
    require('../../assets/actions/fighter-attack-3.png'),
    require('../../assets/actions/fighter-attack-4.png'),
    require('../../assets/actions/fighter-attack-5.png'),
  ],
  'Fighter attack effect': [
    require('../../assets/actions/fighter-attack-effect-1.png'),
    require('../../assets/actions/fighter-attack-effect-2.png'),
    require('../../assets/actions/fighter-attack-effect-3.png'),
    require('../../assets/actions/fighter-attack-effect-4.png'),
    require('../../assets/actions/fighter-attack-effect-5.png'),
  ],
  Digging: [
    require('../../assets/actions/digging-1.png'),
    require('../../assets/actions/digging-2.png'),
    require('../../assets/actions/digging-3.png'),
    require('../../assets/actions/digging-4.png'),
    require('../../assets/actions/digging-5.png'),
  ],
  'Digging effect': [
    require('../../assets/actions/digging-effect-1.png'),
    require('../../assets/actions/digging-effect-2.png'),
    require('../../assets/actions/digging-effect-3.png'),
    require('../../assets/actions/digging-effect-4.png'),
    require('../../assets/actions/digging-effect-5.png'),
  ],
  Healing: [
    require('../../assets/actions/healing-1.png'),
    require('../../assets/actions/healing-2.png'),
    require('../../assets/actions/healing-3.png'),
    require('../../assets/actions/healing-4.png'),
    require('../../assets/actions/healing-5.png'),
  ],
  'Healing effect': [
    require('../../assets/actions/healing-effect-1.png'),
    require('../../assets/actions/healing-effect-2.png'),
    require('../../assets/actions/healing-effect-3.png'),
    require('../../assets/actions/healing-effect-4.png'),
    require('../../assets/actions/healing-effect-5.png'),
  ],
  'Gold earned': [
    require('../../assets/actions/gold-earned-1.png'),
    require('../../assets/actions/gold-earned-2.png'),
    require('../../assets/actions/gold-earned-3.png'),
    require('../../assets/actions/gold-earned-4.png'),
    require('../../assets/actions/gold-earned-5.png'),
  ],
  'Gold earned effect': [
    require('../../assets/actions/gold-earned-effect-1.png'),
    require('../../assets/actions/gold-earned-effect-2.png'),
    require('../../assets/actions/gold-earned-effect-3.png'),
    require('../../assets/actions/gold-earned-effect-4.png'),
    require('../../assets/actions/gold-earned-effect-5.png'),
  ],
  'Opening chest': [
    require('../../assets/actions/opening-chest-1.png'),
    require('../../assets/actions/opening-chest-2.png'),
    require('../../assets/actions/opening-chest-3.png'),
    require('../../assets/actions/opening-chest-4.png'),
    require('../../assets/actions/opening-chest-5.png'),
  ],
  'Opening chest effect': [
    require('../../assets/actions/opening-chest-effect-1.png'),
    require('../../assets/actions/opening-chest-effect-2.png'),
    require('../../assets/actions/opening-chest-effect-3.png'),
    require('../../assets/actions/opening-chest-effect-4.png'),
    require('../../assets/actions/opening-chest-effect-5.png'),
  ],
};
